# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_bike', models.CharField(max_length=255)),
                ('made_by', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('birthday', models.DateTimeField()),
                ('birthplace', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organizator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('birthday', models.DateTimeField()),
                ('birthplace', models.CharField(max_length=255)),
                ('bike', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='allinone.Bike')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='allinone.Team'),
        ),
        migrations.AddField(
            model_name='competition',
            name='organizator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allinone.Organizator'),
        ),
        migrations.AddField(
            model_name='competition',
            name='participants',
            field=models.ManyToManyField(to='allinone.Participant'),
        ),
        migrations.AddField(
            model_name='coach',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='allinone.Team'),
        ),
    ]
